name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
      - name: Build
        run: |
          pip install --upgrade pip
          pip install --upgrade build
          python -m build
          pip install dist/*.whl
      - name: Test
        run: |
          python -m unittest discover -s tests
