name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          pip install --upgrade build
          python -m build
          pip install dist/*.whl
      - name: Test
        run: |
          python -m unittest discover -s tests
